"""initial plan b schema

Revision ID: 78f7ab2be8b2
Revises:
Create Date: 2026-09-06 23:06:37.039711
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types live in the application; autogenerate renders them fully qualified.
import src.common.db

revision: str = "78f7ab2be8b2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_selection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("selection_id", sa.String(length=64), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.String(length=512), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("score_version", sa.String(length=16), nullable=False),
        sa.Column("expires_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("activated_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("wallet_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "copy_intents",
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("source_event_id", sa.String(length=64), nullable=False),
        sa.Column("source_wallet", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=48), nullable=True),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("base_mint", sa.String(length=64), nullable=False),
        sa.Column("quote_mint", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("selection_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("created_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("expires_at_utc", src.common.db.UtcDateTime(), nullable=True),
        sa.Column("settled", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("intent_id"),
    )
    with op.batch_alter_table("copy_intents", schema=None) as batch_op:
        batch_op.create_index("ix_copy_intents_event", ["source_event_id"], unique=False)
        batch_op.create_index("ix_copy_intents_open", ["settled", "decision"], unique=False)
        batch_op.create_index("ix_copy_intents_reason", ["reason_code"], unique=False)
        batch_op.create_index(
            "uq_copy_intents_event_execute",
            ["source_event_id"],
            unique=True,
            sqlite_where=sa.text("decision = 'EXECUTE'"),
        )

    op.create_table(
        "daily_risk_ledger",
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("quote_deployed_raw", sa.String(length=40), nullable=False),
        sa.Column("realized_pnl_quote_raw", sa.String(length=40), nullable=False),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("day"),
    )
    op.create_table(
        "execution_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("broker", sa.String(length=8), nullable=False),
        sa.Column("started_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("finished_at_utc", src.common.db.UtcDateTime(), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intent_id", "attempt", name="uq_execution_attempts_intent_attempt"),
    )
    with op.batch_alter_table("execution_attempts", schema=None) as batch_op:
        batch_op.create_index("ix_execution_attempts_open", ["finished_at_utc"], unique=False)

    op.create_table(
        "execution_results",
        sa.Column("result_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("broker", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("economically_effective", sa.Boolean(), nullable=False),
        sa.Column("signature", sa.String(length=96), nullable=True),
        sa.Column("finished_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("result_id"),
        sa.UniqueConstraint("intent_id", "attempt", name="uq_execution_results_intent_attempt"),
    )
    with op.batch_alter_table("execution_results", schema=None) as batch_op:
        batch_op.create_index("ix_execution_results_status", ["status"], unique=False)
        batch_op.create_index(
            "uq_execution_results_effective",
            ["intent_id"],
            unique=True,
            sqlite_where=sa.text("economically_effective = 1"),
        )

    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("requested_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("expires_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("in_amount_raw", sa.String(length=40), nullable=False),
        sa.Column("out_amount_raw", sa.String(length=40), nullable=False),
        sa.Column("price_impact_bps", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.create_index("ix_quotes_intent", ["intent_id"], unique=False)

    op.create_table(
        "raw_chain_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signature", sa.String(length=96), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("wallet_hint", sa.String(length=64), nullable=True),
        sa.Column("received_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("processed_at_utc", src.common.db.UtcDateTime(), nullable=True),
        sa.Column("decode_failed", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signature", name="uq_raw_chain_events_signature"),
    )
    with op.batch_alter_table("raw_chain_events", schema=None) as batch_op:
        batch_op.create_index("ix_raw_chain_events_slot", ["slot"], unique=False)
        batch_op.create_index("ix_raw_chain_events_unprocessed", ["processed_at_utc"], unique=False)

    op.create_table(
        "service_checkpoints",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "source_wallet_positions",
        sa.Column("source_wallet", sa.String(length=64), nullable=False),
        sa.Column("base_mint", sa.String(length=64), nullable=False),
        sa.Column("base_amount_raw", sa.String(length=40), nullable=False),
        sa.Column("quote_cost_raw", sa.String(length=40), nullable=False),
        sa.Column("quote_proceeds_raw", sa.String(length=40), nullable=False),
        sa.Column("opened_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("updated_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("source_wallet", "base_mint"),
    )
    with op.batch_alter_table("source_wallet_positions", schema=None) as batch_op:
        batch_op.create_index("ix_positions_mint", ["base_mint"], unique=False)

    op.create_table(
        "swap_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.String(length=96), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("block_time_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("wallet", sa.String(length=64), nullable=False),
        sa.Column("base_mint", sa.String(length=64), nullable=False),
        sa.Column("quote_mint", sa.String(length=64), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("base_amount_raw", sa.String(length=40), nullable=False),
        sa.Column("quote_amount_raw", sa.String(length=40), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("instruction_path", sa.String(length=32), nullable=False),
        sa.Column("net_swap_index", sa.Integer(), nullable=False),
        sa.Column("decode_confidence", sa.String(length=16), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("received_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("swap_events", schema=None) as batch_op:
        batch_op.create_index("ix_swap_events_mint", ["base_mint"], unique=False)
        batch_op.create_index("ix_swap_events_signature", ["signature"], unique=False)
        batch_op.create_index(
            "ix_swap_events_wallet_time", ["wallet", "block_time_utc"], unique=False
        )

    op.create_table(
        "token_exposure",
        sa.Column("base_mint", sa.String(length=64), nullable=False),
        sa.Column("base_amount_raw", sa.String(length=40), nullable=False),
        sa.Column("quote_cost_raw", sa.String(length=40), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", src.common.db.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("base_mint"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_exposure")
    with op.batch_alter_table("swap_events", schema=None) as batch_op:
        batch_op.drop_index("ix_swap_events_wallet_time")
        batch_op.drop_index("ix_swap_events_signature")
        batch_op.drop_index("ix_swap_events_mint")

    op.drop_table("swap_events")
    with op.batch_alter_table("source_wallet_positions", schema=None) as batch_op:
        batch_op.drop_index("ix_positions_mint")

    op.drop_table("source_wallet_positions")
    op.drop_table("service_checkpoints")
    with op.batch_alter_table("raw_chain_events", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_chain_events_unprocessed")
        batch_op.drop_index("ix_raw_chain_events_slot")

    op.drop_table("raw_chain_events")
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.drop_index("ix_quotes_intent")

    op.drop_table("quotes")
    with op.batch_alter_table("execution_results", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_execution_results_effective", sqlite_where=sa.text("economically_effective = 1")
        )
        batch_op.drop_index("ix_execution_results_status")

    op.drop_table("execution_results")
    with op.batch_alter_table("execution_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_execution_attempts_open")

    op.drop_table("execution_attempts")
    op.drop_table("daily_risk_ledger")
    with op.batch_alter_table("copy_intents", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_copy_intents_event_execute", sqlite_where=sa.text("decision = 'EXECUTE'")
        )
        batch_op.drop_index("ix_copy_intents_reason")
        batch_op.drop_index("ix_copy_intents_open")
        batch_op.drop_index("ix_copy_intents_event")

    op.drop_table("copy_intents")
    op.drop_table("active_selection")
    # ### end Alembic commands ###
